#
#
#
class profile::lancache::dns {
    # Tools
    package { 'bind-tools': }

    $cache_zones = {
        'assetcdn.101.arenanetworks.com'                => 'redirect',
        'assetcdn.102.arenanetworks.com'                => 'redirect',
        'assetcdn.103.arenanetworks.com'                => 'redirect',
        'dist.blizzard.com'                             => 'redirect',
        'dist.blizzard.com.edgesuite.net'               => 'redirect',
        'llnw.blizzard.com'                             => 'redirect',
        'edgecast.blizzard.com'                         => 'redirect',
        'blizzard.vo.llnwd.net'                         => 'redirect',
        'blzddist1-a.akamaihd.net'                      => 'redirect',
        'blzddist2-a.akamaihd.net'                      => 'redirect',
        'blzddist3-a.akamaihd.net'                      => 'redirect',
        'blzddist4-a.akamaihd.net'                      => 'redirect',
        'level3.blizzard.com'                           => 'redirect',
        'nydus.battle.net'                              => 'redirect',
        'edge.blizzard.top.comcast.net'                 => 'redirect',
        'cdn.blizzard.com'                              => 'redirect',
        'pls.patch.daybreakgames.com'                   => 'redirect',
        'ccs.cdn.wup.shop.nintendo.com'                 => 'redirect',
        'pushmo.hac.lp1.eshop.nintendo.net'             => 'redirect',
        'ecs-lp1.hac.shop.nintendo.net'                 => 'redirect',
        'receive-lp1.dg.srv.nintendo.net'               => 'redirect',
        'aqua.hac.lp1.d4c.nintendo.net'                 => 'redirect',
        'atum.hac.lp1.d4c.nintendo.net'                 => 'redirect',
        'bugyo.hac.lp1.eshop.nintendo.net'              => 'redirect',
        'tagaya.hac.lp1.eshop.nintendo.net'             => 'redirect',
        'origin-a.akamaihd.net'                         => 'redirect',
        'akamai.cdn.ea.com'                             => 'redirect',
        'lvlt.cdn.ea.com'                               => 'redirect',
        'river.data.ea.com'                             => 'redirect',
        'origin-a.akamaihd.net.edgesuite.net'           => 'redirect',
        'rxp-fl.cncirc.net'                             => 'redirect',
        'rxp-chi.cncirc.net'                            => 'redirect',
        'rxp-nz.cncirc.net'                             => 'redirect',
        'rxp-bgr.cncirc.net'                            => 'redirect',
        'rxp-fr.cncirc.net'                             => 'redirect',
        'rxp-nyc.cncirc.net'                            => 'redirect',
        'rxp-uk.cncirc.net'                             => 'redirect',
        'rxp-sg.cncirc.net'                             => 'redirect',
        'rxp-la.cncirc.net'                             => 'redirect',
        'rxp-fin.cncirc.net'                            => 'redirect',
        'denver1.renegade-x.com'                        => 'redirect',
        'l3cdn.riotgames.com'                           => 'redirect',
        'worldwide.l3cdn.riotgames.com'                 => 'redirect',
        'riotgamespatcher-a.akamaihd.net'               => 'redirect',
        'riotgamespatcher-a.akamaihd.net.edgesuite.net' => 'redirect',
        'lol.dyn.riotcdn.net'                           => 'redirect',
        'pls.patch.station.sony.com'                    => 'redirect',
        'gs2.ww.prod.dl.playstation.net'                => 'redirect',
        'content1.steampowered.com'                     => 'redirect',
        'content2.steampowered.com'                     => 'redirect',
        'content3.steampowered.com'                     => 'redirect',
        'content4.steampowered.com'                     => 'redirect',
        'content5.steampowered.com'                     => 'redirect',
        'content6.steampowered.com'                     => 'redirect',
        'content7.steampowered.com'                     => 'redirect',
        'content8.steampowered.com'                     => 'redirect',
        'cs.steampowered.com'                           => 'redirect',
        'steamcontent.com'                              => 'redirect',
        'client-download.steampowered.com'              => 'redirect',
        'content-origin.steampowered.com'               => 'redirect',
        'clientconfig.akamai.steamtransparent.com'      => 'redirect',
        'steampipe.akamaized.net'                       => 'redirect',
        'edgecast.steamstatic.com'                      => 'redirect',
        'steam.apac.qtlglb.com.mwcloudcdn.com'          => 'redirect',
        'cdn1-sea1.valve.net'                           => 'redirect',
        'cdn2-sea1.valve.net'                           => 'redirect',
        'steam.apac.qtlglb.com'                         => 'redirect',
        'edge.steam-dns.top.comcast.net'                => 'redirect',
        'edge.steam-dns-2.top.comcast.net'              => 'redirect',
        'steam.naeu.qtlglb.com'                         => 'redirect',
        'steampipe-kr.akamaized.net'                    => 'redirect',
        'steam.ix.asn.au'                               => 'redirect',
        'steam.eca.qtlglb.com'                          => 'redirect',
        'steam.cdn.on.net'                              => 'redirect',
        'update5.dota2.wmsj.cn'                         => 'redirect',
        'update2.dota2.wmsj.cn'                         => 'redirect',
        'update6.dota2.wmsj.cn'                         => 'redirect',
        'update3.dota2.wmsj.cn'                         => 'redirect',
        'update1.dota2.wmsj.cn'                         => 'redirect',
        'update4.dota2.wmsj.cn'                         => 'redirect',
        'update5.csgo.wmsj.cn'                          => 'redirect',
        'update2.csgo.wmsj.cn'                          => 'redirect',
        'update4.csgo.wmsj.cn'                          => 'redirect',
        'update3.csgo.wmsj.cn'                          => 'redirect',
        'update6.csgo.wmsj.cn'                          => 'redirect',
        'update1.csgo.wmsj.cn'                          => 'redirect',
        'st.dl.bscstorage.net'                          => 'redirect',
        'cdn.mileweb.cs.steampowered.com.8686c.com'     => 'redirect',
        'd3rmjivj4k4f0t.cloudfront.net'                 => 'redirect',
        'addons.forgesvc.net'                           => 'redirect',
        'media.forgecdn.net'                            => 'redirect',
        'files.forgecdn.net'                            => 'redirect',
        'dl1.wargaming.net'                             => 'redirect',
        'dl2.wargaming.net'                             => 'redirect',
        'wg.gcdn.co'                                    => 'redirect',
        'wgusst-na.wargaming.net'                       => 'redirect',
        'wgusst-eu.wargaming.net'                       => 'redirect',
        'update-v4r4h10x.worldofwarships.com'           => 'redirect',
        'wgus-wotasia.wargaming.net'                    => 'redirect',
        'dl-wot-ak.wargaming.net'                       => 'redirect',
        'dl-wot-gc.wargaming.net'                       => 'redirect',
        'dl-wot-se.wargaming.net'                       => 'redirect',
        'dl-wot-cdx.wargaming.net'                      => 'redirect',
        'dl-wows-ak.wargaming.net'                      => 'redirect',
        'dl-wows-gc.wargaming.net'                      => 'redirect',
        'dl-wows-se.wargaming.net'                      => 'redirect',
        'dl-wows-cdx.wargaming.net'                     => 'redirect',
        'dl-wowp-ak.wargaming.net'                      => 'redirect',
        'dl-wowp-gc.wargaming.net'                      => 'redirect',
        'dl-wowp-se.wargaming.net'                      => 'redirect',
        'dl-wowp-cdx.wargaming.net'                     => 'redirect',
        'officecdn.microsoft.com'                       => 'redirect',
        'windowsupdate.com'                             => 'redirect',
        'dl.delivery.mp.microsoft.com'                  => 'redirect',
        'assets1.xboxlive.com'                          => 'redirect',
        'assets2.xboxlive.com'                          => 'redirect',
        'dlassets.xboxlive.com'                         => 'redirect',
        'xboxone.loris.llnwd.net'                       => 'redirect',
        'xboxone.vo.llnwd.net'                          => 'redirect',
        'xbox-mbr.xboxlive.com'                         => 'redirect',
        'assets1.xboxlive.com.nsatc.net'                => 'redirect',
    }

    $stub_zones = {
        "grantcohoe.com" => {
            address  => '192.168.1.1',
            insecure => true,
        }
    }

    class { 'unbound':
        interface               => ['0.0.0.0'],
        access                  => [
            '10.0.0.0/8',
            '::1',
            '192.168.0.0/16',
            '172.16.0.0/12'
        ],
        local_zone              => $cache_zones,
        skip_roothints_download => true,
    }

    Unbound::Record {
        ttl     => 60,
        type    => 'A',
        content => $::ipaddress
    }

    $cache_zones.keys.each |String $zone| {
        unbound::record { $zone: }
    }

    create_resources(unbound::stub, $stub_zones)
}