version: "3"
services:
    puppetserver:
        container_name: puppet
        hostname: puppet
        image: puppet/puppetserver-standalone
        network_mode: "host"
        volumes:
            - "~/Projects/CFCC/TurboPuppet:/etc/puppetlabs/code/environments/production"
            - "~/Projects/CFCC/puppetserver/roles/r10k/files/r10k.yaml:/etc/puppetlabs/r10k/r10k.yaml"
            - "~/Projects/CFCC/puppetserver/roles/fileserver/files/fileserver.conf:/etc/puppetlabs/puppet/fileserver.conf"
            - "/media/CampFitch/PuppetFS:/mnt/PuppetFS"
            - "~/Projects/CFCC/puppetserver-ssl:/etc/puppetlabs/puppet/ssl/"
        environment:
            - DNS_ALT_NAMES=seefra.boston.grantcohoe.com
            - CA_HOSTNAME=seefra.boston.grantcohoe.com
            - PUPPETSERVER_HOSTNAME=seefra.boston.grantcohoe.com