# https://hub.docker.com/r/steamcache/monolithic
version: "3"
services:
  lancache:
    container_name: lancache
    hostname: lancache
    image: steamcache/monolithic
    network_mode: "host"
    volumes:
      - "/tmp/cache/data:/data/cache"
      - "/tmp/cache/logs:/data/logs"
  sniproxy:
    container_name: sniproxy
    hostname: sniproxy
    image: steamcache/sniproxy
    network_mode: "host"
  steamcache-dns:
    container_name: steamcache-dns
    hostname: steamcache-dns
    image: steamcache/steamcache-dns
    network_mode: "host"
    environment:
      - USE_GENERIC_CACHE=true
      - LANCACHE_IP=192.168.1.103